Improve filter bad words
steamforvietnam/Live-at-STEAM pull request #110
Opened 2020-09-06 05:01 UTC by baoc75

Known issues: bad words with "*" character won't work and will drop the entire message.

2020-09-06 06:18 UTC, vudung45 commented on backend/src/chat_server/utils.ts
> +    var get = badwords[i].slice(0, -1).replace(/([a-z])/g, "$1[^a-z]*") + badwords[i].slice(-1);
don't understand what this does

2020-09-06 06:24 UTC, vudung45 approved these changes

2020-09-06 06:24 UTC, vudung45 commented on backend/src/chat_server/utils.ts
> +  return message;
I could be missing a lot of edge cases, but why couldn't we just write something like this?
```suggestion
  BadWordsData.bad_words.map(w => w.trim().toLowerCase()).forEach(w => message = message.replaceAll(w.toLowerCase(), "*".repeat(w.length()))
  return message;
```

2020-09-06 07:03 UTC, baoc75 commented on backend/src/chat_server/utils.ts
> +    var get = badwords[i].slice(0, -1).replace(/([a-z])/g, "$1[^a-z]*") + badwords[i].slice(-1);
Well I was trying to achieve a filter using regex. It loops through the badwords array, then the variable get will turn badwords into a regex string and then we finally replace it too ****.
For example if the current badwords is: f.u.c.k
Then the get string will be: /f[^a-z]*u[^a-z]*c[^a-z]*k/g

2020-09-06 07:05 UTC, baoc75 commented on backend/src/chat_server/utils.ts
> +  return message;
I've ran your solution and it have worked well. Just finished my lunch so I'll start with Jest right now.

2020-09-06 07:07 UTC, baoc75 commented on backend/src/chat_server/utils.ts
> +  return message;
You right, your approach is much more readable and easier to understand by the way :+1: But I'll try to firgue out if there is any benifits of using my approach

2020-09-06 07:08 UTC, vudung45 commented on backend/src/chat_server/utils.ts
> +    var get = badwords[i].slice(0, -1).replace(/([a-z])/g, "$1[^a-z]*") + badwords[i].slice(-1);
I see

2020-09-06 07:08 UTC, vudung45 commented on backend/src/chat_server/utils.ts
> +  return message;
I think you can incoperate ur regex with what I've suggested.

In stead of replacing the string, build a regexp like what you did up there.

2020-09-06 07:28 UTC, baoc75 commented on backend/src/chat_server/utils.ts
> +  return message;
Hmm, I don't really understand, if I build a regexp I still need to replace the string to ***. Would you mind explain it more clearly?

2020-09-07 00:18 UTC, vudung45 commented on backend/src/chat_server/utils.ts
> +  return message;
<img width="1411" alt="Screen Shot 2020-09-06 at 5 17 09 PM" src="https://user-images.githubusercontent.com/5696959/92338402-01c0d800-f065-11ea-9652-6d0b87974f7b.png">

```javascript
BadWordsData.bad_words.map(w => [new RegExp(w.trim().split("").join("[^a-z]*"), "ig"), w.length]).forEach(wordRegexAndLength => message = message.replace(wordRegexAndLength[0], "*".repeat(wordRegexAndLength[1])));
```

2020-09-07 00:20 UTC, vudung45 commented on backend/src/chat_server/utils.ts
> +  return message;
Of course break that code up, put comments for readability, but I think that should work. Let me know if there is any issue.

2020-09-07 01:36 UTC, baoc75 commented on backend/src/chat_server/utils.ts
> +  return message;
![image](https://user-images.githubusercontent.com/8294297/92340505-d2ea4680-f0e4-11ea-85e4-6070898a5973.png)
I've tested with Jest and all passed. I've searched Google about lint and there is library for that, however, if we have any installed library, that would be great!

2020-09-07 01:49 UTC, baoc75 commented on backend/src/chat_server/utils.ts
> +    var get = badwords[i].slice(0, -1).replace(/([a-z])/g, "$1[^a-z]*") + badwords[i].slice(-1);
This will solve the * issue I believe, but I still don't know is there anyway to but a ternary operator in object property?
`badwords.map(w => [new RegExp(w.trim().split("").**((w == "*") ? join("[^a-z]*\\*") : join("[^a-z]*"))**, "ig"), w.length]).forEach(wordRegexAndLength => message = message.replace(wordRegexAndLength[0], "*".repeat(wordRegexAndLength[1])));`

2020-09-07 01:51 UTC, baoc75 commented
This will solve the * issue I believe, but I still don't know is there anyway to but a ternary operator in object property?
`badwords.map(
w => [
 new RegExp(w.trim().split("").
 ((w == "*") ? join("[^a-z]*\\*") : join("[^a-z]*")), "ig"), w.length
])
.forEach(
 wordRegexAndLength => message = message.replace(wordRegexAndLength[0], "*".repeat(wordRegexAndLength[1]))
);`

2020-09-07 02:09 UTC, vudung45 commented
@baoc75 you can try to escape these characters first

e.g `f*k` -> `f\*k`.

Then write a function go split these characters `f\*k` -> `['f', `\*`, 'k']

2020-09-08 17:27 UTC, baoc75 commented
```javascript
export function filterMessage(message) {
  const special = /[ `!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/; //Special Character Array
  var word;
  for (var i = 0; i < badwords.length; i++) {
    word = ""; //
    for (var j = 0; j < badwords[i].length-1; j++) { //Loop through each character of bad words
      word = word + (!special.test(badwords[i][j]) ? badwords[i][j] : "\\"+badwords[i][j]) + "[^a-z]*"; //Build a regex string and try to escape special characters
    }
    word = word + (!special.test(badwords[i][j]) ? badwords[i][j] : "\\" + badwords[i][j]);
    var wordRegex = new RegExp(word, "ig");
    message = message.replace(wordRegex, "*".repeat(badwords[i].length)); //Replace it
  }
  return message;
}
```

2020-09-08 17:37 UTC, baoc75 commented
But I still can't push now for a reason: I was trying to remove bad-words entirely from live app. However, the server.ts file contains the Socket events that use Filter from 'bad-words'. Need to investigate more to safely replace it.

However, due to limited time, I think **we should keep 'bad-words'** right there, **only modify the message_event to use filterMessage() function** and it will work fine. I'll try to remove it on this weekend.

2020-09-08 19:20 UTC, vudung45 commented
@baoc75 the dependency on the current badwords filter implementation shouldn't be that nested.
Also, please consider using `.map()` and `.forEach()` instead of traditional for loop.

2020-09-09 03:44 UTC, baoc75 commented
I have added the helper function but haven't implemented forEach and map which will make it shorter and cleaner. I'll add it to my todo list and try to finish it on this weekend too.

2020-09-09 03:45 UTC, manhhung741 commented on backend/src/chat_server/utils.ts
> +export function createRegexMask(word) {
function nay minh ko dung o ngoai thi ko can export ra ngoai

2020-09-09 03:45 UTC, manhhung741 commented on backend/src/chat_server/utils.ts
> +      "[^a-z]*"; //Build a regex string and try to escape special characters
doan escape special character nay de lam gi the em? can you explain it?

2020-09-09 03:46 UTC, vudung45 commented on backend/src/chat_server/utils.ts
> +      "[^a-z]*"; //Build a regex string and try to escape special characters
@manhhung741 M
basically là `fuck` => sẽ đc mask thành `f[^a-z]*u[^a-z]*c[^a-z]*k`

2020-09-09 03:49 UTC, baoc75 commented on backend/src/chat_server/utils.ts
> +      "[^a-z]*"; //Build a regex string and try to escape special characters
Em phải escape hết special character vì nếu ko nó sẽ bị invalid regexp ấy anh, do là nó đc mask như anh @vudung45 có nói

2020-09-09 03:50 UTC, baoc75 commented on backend/src/chat_server/utils.ts
> +export function createRegexMask(word) {
Em cảm ơn anh ạ, em sẽ sửa lại ạ

2020-09-09 04:00 UTC, baoc75 commented
Em gửi anh @manhhung741 và mọi người test ạ:
``` javascript
const filterMessage = require('./filter.js');

test('1. Words: Dit should be ****', () => {
  expect(filterMessage("địt")).toBe("***");
});

test('2. Words with case: dIt should be ****', () => {
  expect(filterMessage("đỊt")).toBe("***");
});

test('3. Phrase: Lorem Ipsum địt Koan loz cặc should be Lorem Ipsum **** Koan **** ****', () => {
  expect(filterMessage("Lorem Ipsum địt Koan loz cặc")).toBe("Lorem Ipsum *** Koan *** ***");
});

test('4. Normal Phrase: Xin chào các bạn', () => {
  expect(filterMessage("Xin chào các bạn")).toBe("Xin chào các bạn");
});

test('5. Multiple block words in phrase: Cặc loz cmnr sucks trần đức bo hello dcm should be **** **** **** **** **** hello ****', () => {
  expect(filterMessage("Cặc loz cmnr sucks trần đức bo hello dcm")).toBe("*** *** **** ***** *********** hello ***");
});

test('6. Words with addtional prefix: dcme should be ****e', () => {
  expect(filterMessage("dcme")).toBe("***e");
});

test('7. Words with *: d*t should be ***', () => {
  expect(filterMessage("d*t")).toBe("***");
});

test('8. Words with *: *it should be ***', () => {
  expect(filterMessage("*it")).toBe("***");
});

test('9. Words with *: di* should be ***', () => {
  expect(filterMessage("di*")).toBe("***");
});

test('10. Words with special characters: hello ca^c dum@ d!t should be hello *** **** ***', () => {
  expect(filterMessage("hello ca^c dum@ d!t")).toBe("hello *** **** ***");
});

```

2020-09-09 05:20 UTC, manhhung741 commented on backend/src/chat_server/utils.ts
> +      "[^a-z]*"; //Build a regex string and try to escape special characters
Cai `[^a-z]*` co ve se match voi nhieu character lam. Anh nghi at least em nen them cac space characters va numbers. Kieu nhu `[^a-z0-9 \n]*`

2020-09-09 05:55 UTC, vudung45 requested changes

2020-09-09 05:55 UTC, vudung45 commented on backend/src/chat_server/events/message_events.ts
> +      let message = (!(await isAdmin(sessionStore.username))) ? filterMessage(payload.message) : payload.message;
```suggestion
      let message = (!(role == Role.ADMIN) ? filterMessage(payload.message) : payload.message;
```

2020-09-09 06:05 UTC, baoc75 commented on backend/src/chat_server/events/message_events.ts
> +      let message = (!(await isAdmin(sessionStore.username))) ? filterMessage(payload.message) : payload.message;
Thanks a lot @vudung45, I am confused with 2 variables: role và Role. I figured out that javascript variable name is case sensitive.

2020-09-09 06:17 UTC, vudung45 requested changes

2020-09-09 06:17 UTC, vudung45 commented on backend/src/chat_server/events/message_events.ts
> +      let message = (!(role == Role.ADMIN)) ? filterMessage(payload.message) : payload.message;
```suggestion
      let message = (!(role === Role.ADMIN)) ? filterMessage(payload.message) : payload.message;
```

2020-09-09 06:17 UTC, vudung45 approved these changes

2020-09-09 06:24 UTC, merged