Fix message duplication due to optimistic message & refactor PubSubManager
steamforvietnam/Live-at-STEAM pull request #111
Opened 2020-09-07 05:14 UTC by vudung45

…nager

2020-09-07 05:16 UTC, vudung45 commented on frontend/src/Components/Chatbox.tsx
> +          if (messages.some((message) => message.payload.trackId === trackId))
make sure the message hasn't been rendered before adding

2020-09-09 03:51 UTC, manhhung741 approved these changes

2020-09-09 03:51 UTC, manhhung741 commented on frontend/src/Components/Chatbox.tsx
> +          if (messages.some((message) => message.payload.trackId === trackId))
👍

2020-09-09 04:06 UTC, namdaoduy requested changes

2020-09-09 04:06 UTC, namdaoduy commented on frontend/src/Components/Chatbox.tsx
> +          messages.push({
@vudung45 Please create a new array, don't push to the current state

2020-09-09 05:35 UTC, vudung45 commented on frontend/src/Components/Chatbox.tsx
> +          messages.push({
Modifying `messages` directly is actually one of the step to avoid race condition. Say in the scenario where updateMessage() hasn't finished rendering yet, by updating messages directly, it prevents other callbacks from duplicating the message .

2020-09-09 05:45 UTC, manhhung741 commented on frontend/src/Components/Chatbox.tsx
> +          messages.push({
Messages la state thi fai update qua `updateMessage` chu em. 

btw
```
  const [messages, updateMessages] = React.useState([] as Message[]);
``` 
co the sua thanh
```
  const [messages, updateMessages] = React.useState<Message[]>([]);
```

2020-09-09 05:45 UTC, namdaoduy commented on frontend/src/Components/Chatbox.tsx
> +          messages.push({
Already changed. Please rollback or resolve if needed. @vudung45 vu

2020-09-09 05:45 UTC, manhhung741 approved these changes

2020-09-09 05:47 UTC, vudung45 commented on frontend/src/Components/Chatbox.tsx
> +          messages.push({
@manhhung741 e vẫn update bằng updateMessage(),  mà e modify cái messages trước rồi updateMessage([...mesage])

2020-09-09 05:47 UTC, merged