EventTracker
steamforvietnam/Live-at-STEAM pull request #79
Opened 2020-09-03 06:42 UTC by vudung45

Usage example
`
const GAHandler = (eventTracker: { eventName: string, timeFired: number, aux: any}) => {
   // handle send event logger to GA
})
let eventTracker = new EventManager(GAHandler);

eventTracker.register(socket, "message", (payload) => { //add  message tc});

eventTracker.emit("message", "hello cac ban"); // eventTracker will automatically create a tracker for this event, and roundtrip time will be calculated during callback
}
`

2020-09-03 06:53 UTC, namdaoduy commented
@vudung45 As I can see, each type of event will need a different eventTracker?
Because event data is very depends on type of event. Combine them in one tracker will make the code quite hard to read.

2020-09-03 07:01 UTC, vudung45 commented
@namdaoduy Nam
There should be only 1 GAHandler so make them as generic as possible
e.g for GA roundtrip Logger
```
const GAHandler = (eventTracker: { eventName: string, timeFired: number, aux: any}) => {
   ReactGA.event({
          category: `${getEventCategory(eventName)}_roundtrip`,
          action: getEventType(eventName),
          label: Date.now() - eventName,
        });
})
```
GAHandler is fired inside subscriber callback.

2020-09-03 08:13 UTC, namdaoduy requested changes

2020-09-03 08:13 UTC, namdaoduy commented on frontend/src/Utils/EventTracker.ts
> +    handler: (payload: Payload) => any,
handler can be undefined also. Some events also need to be emit.

2020-09-03 08:13 UTC, namdaoduy commented on frontend/src/Utils/EventTracker.ts
> +      return handler(payload);
Check if handler is undefined

2020-09-03 08:13 UTC, vudung45 commented on frontend/src/Utils/EventTracker.ts
> +    handler: (payload: Payload) => any,
subscribe is equivalent to socket.on()
User only calls it when they want to handle callback

2020-09-03 08:13 UTC, vudung45 commented on frontend/src/Utils/EventTracker.ts
> +      return handler(payload);
^

2020-09-03 08:17 UTC, namdaoduy commented on frontend/src/Utils/EventTracker.ts
> +    handler: (payload: Payload) => any,
This usecase:
- User only want to emit an event, no handler needed for incoming event
- User want to track roundtrip on that event
=> Additional handler on `on` is unnecessary. I have to put empty funtion on that handler.
@vudung45

2020-09-03 08:37 UTC, namdaoduy commented on frontend/src/Utils/EventTracker.ts
> +    handler: (payload: Payload) => any,
@vudung45 Sorry, i confused between `register` and `subscribe`. LGTM now!

2020-09-03 08:38 UTC, namdaoduy approved these changes

2020-09-03 08:49 UTC, vudung45 commented on frontend/src/Utils/EventTracker.ts
> +   * Publish a new message to a channel
```suggestion
   * Publish a new message to channel
```

2020-09-05 19:06 UTC, vudung45 commented on frontend/src/Components/Chatbox.tsx
> +  }, [socketTracker, userData.username]);
Let's only resubscribe when socketTracker changes! 

```suggestion
  }, [socketTracker]);
```

2020-09-05 21:25 UTC, manhhung741 commented on backend/userstate.json
> +{
cai file nay tuong minh remove roi

2020-09-05 21:25 UTC, manhhung741 commented on backend/userstate.json
> +{
nho' remove file nay nha.

2020-09-05 21:59 UTC, merged