Add small feature: Admin can't be banned or blocked
steamforvietnam/Live-at-STEAM pull request #80
Opened 2020-09-03 16:56 UTC by baoc75

Cảm ơn các anh chị đã dành thời gian review code của em.
Đây là lần đầu tiên em push code cho một dự án team thế này ạ, không thể không tránh khỏi sai xót.
Mong anh chị góp ý để em chỉnh sửa!

2020-09-03 18:52 UTC, tuanh118 requested changes
We should remove `ban` and `report` options in admin's chat messages as well to avoid confusing users

2020-09-03 18:52 UTC, tuanh118 commented on backend/package.json
> +    "redis": "^3.0.2",
remove this since it's not related to this change
`npm uninstall redis`

2020-09-03 18:52 UTC, tuanh118 commented on backend/src/chat_server/events/report_events.ts
> +        let userState = await UserManager.banUser(username);
It's better to do this check in this shared `UserManager.banUser` function. Because we want to do admin check in other scenarios when a user is banned, like reported multiple times, send profane messages, etc.

2020-09-03 18:52 UTC, tuanh118 commented on backend/src/chat_server/events/report_events.ts
> +      if (isAdmin(username)) {
Similarly, we should do this check in the `UserManager.reportUser` function

2020-09-03 19:06 UTC, vudung45 commented on backend/package.json
> +    "redis": "^3.0.2",
add `--save` as well

2020-09-03 19:07 UTC, vudung45 commented on backend/src/chat_server/events/report_events.ts
> +        let userState = await UserManager.banUser(username);
I personally think it's better to do it at API level since UserManager.banUser is subjected to change!

2020-09-03 19:17 UTC, vudung45 approved these changes
Please resolve my suggestions and push another commit.

I will let you do the merge urself.

2020-09-03 19:17 UTC, vudung45 commented on backend/src/chat_server/events/report_events.ts
> +      }
```suggestion
      if (isAdmin(username)) {
        return this.io.to(socket.id).emit("report_user_resp", {
          status: -1,
          response: `Bạn không thể cấm chat admin ${username}.`,
        });
      }
      let userState = await UserManager.banUser(username);
      this.emitBanMessage(username).catch((e) => console.error(e));
      return this.io.to(socket.id).emit("report_user_resp", {
        status: -1,
        response: `Cấm chat ${username} thành công!`,
      });
```
I personally think making the codeblocks less nested would help with readability a lot :D. Keep in mind that we already have to deal with "callback hell" sometimes so making the code less nested whenever you can would definitely help!

2020-09-03 19:48 UTC, tuanh118 commented on backend/src/chat_server/events/report_events.ts
> +        let userState = await UserManager.banUser(username);
In that case, it's best to create a middle layer that manages the `UserManager` calls, rather than calling these functions here directly.

For this PR, I'm okay with this

2020-09-03 19:49 UTC, tuanh118 commented
> We should remove `ban` and `report` options in admin's chat messages as well to avoid confusing users

The back-end change is good. Let's still make this change in the front-end

2020-09-04 02:28 UTC, baoc75 reviewed
Resolved all comments

2020-09-04 02:30 UTC, baoc75 commented
> We should remove `ban` and `report` options in admin's chat messages as well to avoid confusing users
Should I make that change on a new pull request or complete it here?

2020-09-04 02:49 UTC, baoc75 commented
> We should remove `ban` and `report` options in admin's chat messages as well to avoid confusing users
> The back-end change is good. Let's still make this change in the front-end

I've made change in the front-end. Please take a look at it and approve!

2020-09-04 03:15 UTC, vudung45 approved these changes

2020-09-04 03:15 UTC, vudung45 commented on frontend/src/Components/MessageUI.tsx
> +                  ]}
nit: only add [] when there are more than 1 components.
```suggestion
                  {role === 0 && 
                    <Dropdown.Item
                      className="u-cursorPointer u-alignItemsCenter"
                      role="button"
                      onClick={() => {
                        handleReportUser(username);
                        setShowDropdown(false);
                      }}
                    >
                      <Icon name="flag" size="extraSmall" />
                      <span className="u-marginLeftExtraSmall u-text200 u-textNoWrap">
                        Báo cáo vi phạm
                      </span>
                    </Dropdown.Item>,
                  }
```

2020-09-04 03:23 UTC, baoc75 commented on frontend/src/Components/MessageUI.tsx
> +                  ]}
Thanks @vudung45, I'll update it now

2020-09-04 04:59 UTC, tuanh118 commented on frontend/src/Components/MessageUI.tsx
> +                  {role != 0 && (
add this check for the ban button below as well

2020-09-04 08:15 UTC, vudung45 commented on frontend/src/Components/MessageUI.tsx
> +                  {role != 0 && (
Ohh the ban button is already checked I believe!

2020-09-04 09:13 UTC, baoc75 commented on frontend/src/Components/MessageUI.tsx
> +                  {role != 0 && (
@vudung45 I have the same thought as you. But if we keep like that, then admin still able to press ban/block to an admin user

2020-09-04 09:19 UTC, baoc75 commented on frontend/src/Components/MessageUI.tsx
> +                  {role != 0 && (
Something went wrong, now it even don't allow me to ban/block regular user :o this is so strange

2020-09-04 12:11 UTC, vudung45 approved these changes

2020-09-04 12:11 UTC, vudung45 commented on frontend/src/Components/MessageUI.tsx
> +                    ]}
Admin message is also deletable!
This logic should address it. Please apply this change (if you do it through github UI, make sure to `git pull` on your local machine and commit again for linter to run)

```suggestion
                    <Dropdown.Item
                        className="u-cursorPointer u-alignItemsCenter"
                        role="button"
                        onClick={() => {
                          handleDeleteMessage();
                          setShowDropdown(false);
                        }}
                    >
                        <Icon name="trash" size="extraSmall" />
                        <span className="u-marginLeftExtraSmall u-text200 u-textNoWrap">
                          Xoá tin nhắn
                        </span>
                    </Dropdown.Item>
                    {
                    (userData?.role === 0 || role !== 0) && 
                      <Dropdown.Item
                        className="u-cursorPointer u-alignItemsCenter"
                        role="button"
                        onClick={() => {
                          handleBanUser(username);
                          setShowDropdown(false);
                        }}
                      >
                        <Icon name="micOff" size="extraSmall" />
                        <span className="u-marginLeftExtraSmall u-text200 u-textNoWrap">
                          Cấm chat
                        </span>
                      </Dropdown.Item>,
                    }
```

2020-09-05 02:44 UTC, baoc75 commented on frontend/src/Components/MessageUI.tsx
> +                    ]}
@vudung45 Hi there, I've updated the delete button check to make sure admin message is deletable by admin.

2020-09-05 02:46 UTC, merged

2020-09-05 02:48 UTC, baoc75 commented
Thank you vudung! My first ever commit to master!